# Generated by Django 3.1.7 on 2021-04-09 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0004_auto_20210402_1850'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='text_field',
            field=models.CharField(default='', max_length=10),
            preserve_default=False,
        ),
    ]
