# Generated by Django 3.1.7 on 2021-04-09 17:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0005_book_text_field'),
    ]

    operations = [
        migrations.CreateModel(
            name='Family',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Animal',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('color', models.CharField(choices=[('kuqe', 'Kuqe'), ('blu', 'Blu'), ('bardhe', 'Bardhe')], max_length=100)),
                ('nr_feet', models.IntegerField(default=4)),
                ('vaccinated', models.BooleanField(default=False)),
                ('age', models.IntegerField()),
                ('family', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='book.family')),
            ],
        ),
    ]
