# Generated by Django 3.1.7 on 2021-04-09 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0006_animal_family'),
    ]

    operations = [
        migrations.CreateModel(
            name='BBBB',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.DateField()),
            ],
        ),
        migrations.AddField(
            model_name='family',
            name='a',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='book.bbbb'),
        ),
    ]
