# Generated by Django 3.1.7 on 2021-04-09 17:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0007_auto_20210409_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='animal',
            name='last_visit',
            field=models.DateField(default=datetime.date(2020, 1, 1)),
        ),
    ]
